[package]
name = "wuukoproxy"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
commander = "0.1.5"
tokio = { version = "1", features = ["full"] }

